name: banner_status_internet_connection
description: A package to show internet connection status dynamically with customizable styles and text.
version: 0.0.4
repository: https://github.com/joicodev/banner_status_internet_connection

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider:
  internet_connection_checker_plus: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0