name: elkood_connection_banner
description: A package to show internet connection status dynamically with customizable styles and text.
version: 0.0.6

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  internet_connection_checker_plus: ^2.5.2

dependencies_overrides:
  connectivity_plus: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0